# Generated by Django 5.1.2 on 2024-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0002_produit_seuil_alerte"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="prix_achat",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
