# Generated by Django 5.1.2 on 2024-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("ifu", models.CharField(max_length=20, unique=True)),
                ("adresse", models.TextField()),
                ("telephone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("site_web", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
