# Generated by Django 5.1.2 on 2024-11-10 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertes", "0001_initial"),
        ("produit", "0002_produit_seuil_alerte"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alerte",
            name="seuil_alerte",
        ),
        migrations.AddField(
            model_name="alerte",
            name="date_alerte",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alerte",
            name="message",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alerte",
            name="produit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertes",
                to="produit.produit",
            ),
            preserve_default=False,
        ),
    ]
