# Generated by Django 5.1.2 on 2024-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertes", "0002_remove_alerte_seuil_alerte_alerte_date_alerte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerte",
            name="quantite_restante",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
