# Generated by Django 5.1.2 on 2024-11-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caisse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("payment_number", models.AutoField(primary_key=True, serialize=False)),
                ("date_transaction", models.DateTimeField(auto_now_add=True)),
                ("prix_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
