# Generated by Django 5.1.2 on 2024-11-09 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caisse", "0004_remove_facturation_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturation",
            name="transaction",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facturations",
                to="caisse.transaction",
            ),
            preserve_default=False,
        ),
    ]
