# Generated by Django 5.1.2 on 2024-11-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caisse", "0007_facturation_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facturation",
            old_name="prix_total",
            new_name="total",
        ),
    ]
